<?php
/**
 * Created by Maksim Skliarov.
 * Project: emi-cms
 * Company: Emi-Soft <emi.softdeveloper@gmail.com>
 * Date: 05/09/2018
 */

namespace emi\module;


/**
 * Class DbModuleManager
 * @package emi\module
 */
class DbModuleManager extends ModuleManager
{

    /**
     * @inheritDoc Подключение модулей Приложения при запуске
     */
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $modules = $this->getModules();
        foreach ($modules as $module) {
            $params = $this->sortParams($module);
            $this->setModule($module->key, $params);
        }
    }

    /**
     *
     * @see ModuleManagerInterface::getModule()
     *
     * @param      $id
     * @param bool $params
     * @param bool $active
     *
     * @return array|Module|mixed|null|\yii\db\ActiveRecord
     */
    public function getModule($id, $params = false, $active = true)
    {
        $module = Module::find()->where(['key' => $id, 'status' => $active])->with();

        if ($params) {
            $module->with('params');
        }
        $module = $module->one();
        return $module ? $module : null;
    }

    /**
     *
     * @see ModuleManagerInterface::getModules()
     *
     * @param bool $active
     *
     * @return array|Module[]|\yii\db\ActiveRecord[]
     */
    public function getModules($active = true)
    {
        $modules = Module::find()->where(['status' => $active])->with(['params', 'childModules'])->all();
        return $modules ? $modules : [];
    }


    /**
     *
     * @inheritdoc Получение параметров и модулей в модуле
     *
     * @param $module
     *
     * @return array
     */
    private function sortParams($module)
    {
        $params = [];
        foreach ($module->params as $key => $param) {

            $params[$key] = $param->value;

            if ($module->childModules) {
                foreach ($module->childModules as $childKey => $childModule) {
                    $params['modules'][$childKey] = $this->sortParams($childModule);
                }
            }
        }

        return $params;
    }

}