<?php
/**
 * Created by Maksim Skliarov.
 * Project: emi-cms
 * Company: Emi-Soft <emi.softdeveloper@gmail.com>
 * Date: 03/09/2018
 */

namespace emi\web;


/**
 * Class Application
 * @package emi\web
 *
 */
class Application extends \emi\base\Application
{

    protected function bootstrap()
    {
        parent::bootstrap(); // TODO: Change the autogenerated stub
    }


}